config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: 'users/sessions', passwords: 'users/passwords' } 
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/profile', to: 'users/registrations#profile'
  end
  get '/users/projects/:id', to: 'projects#show'
  resources :projects do
    resources :donate_items
    resources :messages, only: %i[index create]
    member do
      post :follow
    end
    resource :disclosures, only: [:show]
    resources :comments, shallow: true
    resources :questions, shallow: true, except: [:show]
  end
  namespace :api do
    resources :comments, only: [] do
      member do
        post :like
      end
    end
    resource :search, only: [] do 
      collection do
        get :projects
      end 
    end
  end
  resources :follows, only: [:index] 
  resources :transactions, only: [:index, :create, :destroy] do
    collection do
      post :paid
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :project
  validates :title, presence: true
  validates :content, presence: true

end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  before_action :find_question, only: %i[edit update destroy]
  before_action :find_project_by_question, only: %i[edit update destroy]
  before_action :find_project, only: %i[index new create]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = @project.questions.new(params_question)
    if @question.save
      redirect_to project_questions_path(@project.id), notice: '常見問題建立成功'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(params_question)
      redirect_to project_questions_path(@project.id), notice: '常見問題更新成功'
    else
      render :edit, notice: '常見問題更新失敗'
    end
  end

  def destroy
    @question.destroy
    redirect_to project_questions_path(@project.id), notice: '常見問題刪除成功'
  end

  private

  def params_question
    params.require(:question).permit(:title, :content)
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def current_project
    @current_project = current_user.projects.find(params[:project_id])
  end

  def find_project_by_question
    @project = Question.find(params[:id]).project
  end

  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/views/questions/edit.html.erb
<main>
  <section class='py-10 bg-gray-50'>
    <div class="max-w-6xl mx-auto">
      <h1 class="mb-3 text-center"><%= @project.title %></h1>
      <p class="mb-4 text-center">提案者 <span class="primary-text-color"><%= @project.organizer %></span></p>
    </div>
  </section>
  <section class='py-12 reverse-bg'>
    <div class='max-w-3xl px-6 py-3 mx-auto bg-white shadow rounded-2xl'>
      <h2 class="py-4 my-4 text-2xl tracking-wider text-center text-white bg-purple-400 rounded-2xl" >修改常見問題</h2>
      <% if @question.errors.any? %>
        <% @question.errors.full_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      <% end %>
      <%= form_with model: @question do |form| %>
        <div class="form-list">
          <%= form.label :title, "問題主題 *", class:"form-list-label" %>
          <%= form.text_field :title, class:"form-list-field input-focus" %>
        </div>
        <div class="form-list">
          <%= form.label :content, "問題內容 *", class:"form-list-label" %>
          <%= form.text_field :content, class:"form-list-field input-focus" %>
        </div>
          <%= form.submit "確認送出", class:"field bg-purple-400 hover:bg-purple-600 w-full rounded px-6 py-2 text-white" %>
      <% end %>
    </div>  
  </section>
</main>

app/views/questions/index.html.erb
<main>
  <section class='py-10 bg-gray-100'>
    <div class="max-w-6xl mx-auto">
      <h1 class="mb-3 text-2xl text-center text-semibold"><%= @project.title %></h1>
      <p class="mb-4 text-center">提案者 <span class="primary-text-color"><%= @project.organizer %></span></p>
    </div>
  </section>
  <div class='sticky top-0 z-10 bg-white border-t-2 border-b-2 border-gray-200 border-double'>
    <div class="justify-between max-w-6xl mx-auto text-sm md:text-base lg:flex">
      <div class="flex items-center justify-center h-16 font-semibold text-gray-400">
        <%= link_to '專案內容', project_path(@project), class:"mx-2 md:mx-5"%>
        <a href='<%= project_questions_path(@project)%>' class="mx-2 current-page md:mx-5">
          常見問題 <span class='text-xs align-top'><%= @project.questions.count%></span>
        </a>
        <a href='<%= project_comments_path(@project)%>' class="mx-2 md:mx-5">
          留言專區 <span class='text-xs align-top'><%= @project.comments.count%></span>
        </a>
        <%= link_to '即時通訊', project_messages_path(@project), class:"mx-2 md:mx-5"%>
      </div>  
      <% if @project.user_id == current_user&.id %>
        <div class='mb-4 text-center lg:my-3'>
          <%= link_to "新增常見問題", new_project_question_path(@project.id), class:'mx-5 p-2 inline-block border border-purple-400 rounded-xl' %>
        </div>
      <% end %>
    </div>
  </div>
  <%# 常見問題區 %>
  <section class='py-8 border-b-2 border-gray-300 border-double'>
    <div class="max-w-xl grid-cols-10 gap-12 px-3 mx-auto lg:max-w-6xl lg:grid">
      <div class="col-span-7 accordion" data-controller='questionSwitch'>
        <% @project.questions.each.with_index do |question,index| %>
          <article class="contentBox" data-questionSwitch-target='btn' data-action='click->questionSwitch#switch' data-index=<%= index %>>
            <div class="contentTitle">
              <h2><span class="mr-8">Q<%= question.id%></span><%= question.title %></h2>
            </div>
            <div class="content">
              <p><%= question.content %></p>
              <div class='flex justify-between mt-2'>  
                <p class='text-sm text-gray-400'>最後更新時間 <%= question.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
                <% if @project.user_id == current_user&.id %>  
                  <div>
                    <%= link_to "編輯", edit_question_path(question.id), class:'mr-3'%>
                    <%= link_to "刪除", question, method: 'delete' %>
                  </div>
                <% end %> 
              </div>
            </div>
          </article>
        <% end %>
      </div>
      <%# silde-bar %>
      <div class='col-span-3 '>
        <article class='w-full p-4 border border-gray-300 border-solid rounded-xl'>
          <div class='flex'>
           <% if @project.user.avatar_url != nil %>
              <%= image_tag(@project.user.avatar_url, :class=> "rounded-2xl h-20 w-20 mr-3") %>
            <% else %>
              <%= image_tag 'avatar1.png', class: 'rounded-2xl h-20 w-20 mr-3' %>
            <% end %>
            <div>
              <h2 class='mb-3 text-xl primary-text-color'><%= @project.organizer %></h2>
              <i class="mr-2 text-2xl fa-brands fa-square-facebook"></i>
              <i class="text-2xl fa-brands fa-instagram"></i>
            </div>
          </div>
          <p class='mb-3 break-words'><%= @project.user.description%></p>
        </article>
      </div>
    </div>  
  </section>
</main>  

app/views/questions/new.html.erb
<main>
  <section class='py-10 bg-gray-100'>
    <div class="max-w-6xl mx-auto">
      <h2 class="mb-3 text-center"><%= @project.title %></h2>
      <p class="mb-6 text-center">提案組織 <span class="primary-text-color"><%= @project.organizer %></span></p>
    </div>
  </section>
  <section class='py-10 wave-bg'>
    <div class='max-w-3xl p-6 mx-auto bg-white md:py-8'>
      <h2 class="py-4 my-4 text-2xl tracking-wider text-center text-white bg-purple-400 rounded-2xl" >新增常見問題</h2>
      <% if @question.errors.any? %>
        <% @question.errors.full_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      <% end %>
      <%= form_with model: @question, url: project_questions_path(@project.id) do |form| %>
        <div class="form-list">
          <%= form.label :title, "問題主題 *", class:"form-list-label" %>
          <%= form.text_field :title, class:"form-list-field input-focus" %>
        </div>
        <div class="form-list">
          <%= form.label :content, "問題內容 *", class:"form-list-label" %>
          <%= form.text_field :content, class:"form-list-field input-focus" %>
        </div>
          <%= form.submit "確認送出", class:"field bg-purple-400 hover:bg-purple-600 w-full rounded px-6 py-2 text-white" %>
      <% end %>
    </div>  
  </section>
</main>