config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: 'users/sessions', passwords: 'users/passwords' } 
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/profile', to: 'users/registrations#profile'
  end
  get '/users/projects/:id', to: 'projects#show'
  resources :projects do
    resources :donate_items
    resources :messages, only: %i[index create]
    member do
      post :follow
    end
    resource :disclosures, only: [:show]
    resources :comments, shallow: true
    resources :questions, shallow: true, except: [:show]
  end
  namespace :api do
    resources :comments, only: [] do
      member do
        post :like
      end
    end
    resource :search, only: [] do 
      collection do
        get :projects
      end 
    end
  end
  resources :follows, only: [:index] 
  resources :transactions, only: [:index, :create, :destroy] do
    collection do
      post :paid
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @project = Project.find(params[:project_id])
    @messages = @project.messages
    @message = Message.new
    has_donated?(@project, current_user)
  end

  def create
    @message = current_user.messages.new(params_message)
    @message.save!
    @project = Project.find(params[:project_id])
    SendMessageJob.perform_now(@message, @project)
  end

  private

  def params_message
    params.require(:message).permit(:content, :project_id, :user_id)
  end

  def has_donated?(project, user)
    @donated = Transaction.find_by(project_id: project, user_id: user).present?
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<div class='grid items-center grid-cols-8 pr-2 mb-4'>
  <div class='col-span-1'>
    <%= image_tag 'avatar1.png', class: 'rounded-2xl h-12 w-12 mr-1 ' %>
  </div>
  <div class='col-span-7 p-1 bg-purple-100 rounded-lg '>
    <p class='flex justify-between text-lg'> <%= message.user.username %><span class='ml-2 text-base text-right text-gray-400'><%= message.created_at.strftime(('%Y-%m-%d %H:%M'))%></span></p>
    <p class='w-full px-3 text-xl text-white break-all bg-gray-400 rounded-xl'><%= message.content %></p>
  </div>
</div>  

app/views/messages/index.html.erb
<main class=''>
  <section class='py-10 bg-gray-100'>
    <div class="max-w-6xl mx-auto">
      <h2 class="mb-3 text-2xl text-center text-semibold"><%= @project.title %></h2>
      <p class="mb-4 text-center">提案組織 <span class="primary-text-color"><%= @project.organizer %></span></p>
    </div>
  </section>
  <div class="px-5 bg-white border-t-2 border-b-2 border-gray-300 border-double " >
    <div class="justify-between max-w-6xl mx-auto text-sm md:text-base lg:flex">
      <div class="flex items-center justify-center h-16 font-semibold text-gray-400">
        <%= link_to '專案內容', project_path(@project), class:"mx-2 md:mx-5"%>
        <a href='<%= project_questions_path(@project)%>' class="mx-2 md:mx-5">
          常見問題 <span class='text-xs align-top '><%= @project.questions.count%></span>
        </a>
        <a href='<%= project_comments_path(@project)%>' class="mx-2 md:mx-5 ">
          留言專區 <span class='text-xs align-top '><%= @project.comments.count%></span>
        </a>
        <%= link_to '即時通訊', project_messages_path(@project), class:"mx-2 md:mx-5 current-page"%>
      </div> 
    </div>  
  </div>
  <section class='py-8 border-b-2 border-gray-300 border-double'>
    <div class="max-w-6xl grid-cols-10 gap-12 mx-auto lg:grid ">
      <% if @donated || current_user.id == @project.user.id %>
        <div class="col-span-5 col-start-2 px-3 mb-3 lg:shadow-xl accordion" data-controller='messageList' data-project-id=<%= @project.id %>>
          <div data-messageList-target='box' class='overflow-x-hidden overflow-y-auto h-450' id='box'>
            <div data-messageList-target='message' class='p-4 rounded-xl'>
              <% @project.messages.each do |message| %>
                <%= render 'messages/message', message: message %>  
              <% end %>
            </div>
          </div>
          <%= form_with(model: @message, url: project_messages_path(@project.id), method: 'post',
                        local: true,
                        data: { action: 'ajax:success->messageList#clearInput'},
                        data: { action: 'submit->messageList#bottom'}
              ) do |form| %>
            <%= form.hidden_field :project_id, value: @project.id %>
            <%= form.hidden_field :user_id, value: @project.user_id %>
            <div class='flex p-2 mx-auto w-max'>
              <%= form.text_field :content, data: { 'messageList-target': 'input' }, class:'py-3 input-focus mx-1 bg-gray-200', placeholder:'輸入訊息'%>
              <%= button_tag type: 'submit', data: {disable_with: false}, class: 'text-purple-400 hover:text-purple-600 py-2 pl-3 pr-4 rounded-full border border-purple-400', data: { action: ''} do %>
                <i class="text-lg fa-solid fa-paper-plane"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      <% else %>
        <p class='col-span-5 col-start-2 mb-16 text-center pt-11 '>請先 <%= link_to '贊助專案', project_donate_items_path(@project) , class:'primary-text-color text-lg p-2 border border-purple-300 rounded-xl hover:bg-purple-400 hover:text-white'%> 即可開通即時通訊</p>
      <% end %>
      <div class='col-span-3 col-end-11 '>
        <article class='w-full p-4 border border-gray-300 border-solid rounded-xl'>
          <div class='flex'>
            <% if @project.user.avatar_url != nil %>
              <%= image_tag(@project.user.avatar_url, :class=> "rounded-2xl h-20 w-20 mr-3") %>
            <% else %>
              <%= image_tag 'avatar1.png', class: 'rounded-2xl h-20 w-20 mr-3' %>
            <% end %>
            <div>
              <h2 class='mb-3 text-xl primary-text-color'><%= @project.organizer %></h2>
              <i class="mr-2 text-2xl fa-brands fa-square-facebook"></i>
              <i class="text-2xl fa-brands fa-instagram"></i>
            </div>
          </div>
          <p class='mb-3 break-words'><%= @project.user.description%></p>
        </article>
      </div>
    </div>  
  </section>
</main> 