config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: 'users/sessions', passwords: 'users/passwords' } 
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/profile', to: 'users/registrations#profile'
  end
  get '/users/projects/:id', to: 'projects#show'
  resources :projects do
    resources :donate_items
    resources :messages, only: %i[index create]
    member do
      post :follow
    end
    resource :disclosures, only: [:show]
    resources :comments, shallow: true
    resources :questions, shallow: true, except: [:show]
  end
  namespace :api do
    resources :comments, only: [] do
      member do
        post :like
      end
    end
    resource :search, only: [] do 
      collection do
        get :projects
      end 
    end
  end
  resources :follows, only: [:index] 
  resources :transactions, only: [:index, :create, :destroy] do
    collection do
      post :paid
    end
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  has_many :donate_items, dependent: :destroy
  has_many :transactions, dependent: :destroy
  has_rich_text :description
  has_one_attached :avatar
  has_many :comments, dependent: :destroy
  has_many :follows, as: :followable, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :organizer, :email, :phone, :title, :amount_target, :end_time,
            :description, :avatar, presence: true
  validates :avatar, attached: true, content_type: ['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/gif']
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  include PriceSumable

  before_action :authenticate_user!, except: %i[index show]
  before_action :find_project, only: %i[show edit destroy update follow]

  def index
    @projects = Project.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @projects }
    end
  end

  def new
    @project = Project.new
  end

  def edit; end

  def destroy
    if @project.really_destroy!
      redirect_to '/projects', notice: '提案刪除成功 !!'
    else
      redirect_to '/projects', notice: '不能刪除 !!'
    end
  end

  def show
    @comment = Comment.new
    @comments = @project.comments.order(id: :desc)

    @donate_items = @project.donate_items.order(created_at: :asc)

    @donate_users_count = Transaction.where(project_id: @project.id).select(:user_id).map(&:user_id).uniq.count

    @follow_state = follow_list.empty? ? '追蹤專案' : '取消追蹤'

    project_current_total(params[:id])
    percentage_of_currency(params[:id])
  end

  def update
    if @project.update(project_params)
      redirect_to project_path, notice: ' 提案更新成功 !!'
    else
      render :edit
    end
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      redirect_to new_project_donate_item_path(@project.id), notice: ' 提案成功 !!'
    else
      render :new
    end
  end

  def follow
    follow_list.empty? ? add_follow : cancel_follow
  end

  private

  def project_params
    params.require(:project).permit(
      :organizer, 
      :email, 
      :phone, 
      :title, 
      :amount_target, 
      :end_time, 
      :description,
      :avatar,
    )
  end

  def find_project
    @project = Project.find(params[:id])
  end

  def follow_list
    Follow.current_user_follow_this_project(current_user&.id, params)
  end

  def add_follow
    @project.follows.create(:user_id => current_user.id, :mail_sent => "false")
    render json: { status: "been_followed" }
  end

  def cancel_follow
    follow_list.first.destroy
    render json: { status: 'cancel_follow' }
  end
end

app/views/projects/edit.html.erb
<main class='reverse-bg'>
  <% if @project.errors.any? %> 
    <div class='py-6'>
      <p class='text-center'>資料有誤，請填寫正確格式：</p>
      <ul class='text-red-400'>
        <% @project.errors.full_messages.each do |message| %>
          <li class="text-center error_message"><%= message %></li> 
        <% end %> 
      </ul>
    </div>  
  <% end %>
  <div class='max-w-3xl py-12 mx-auto '>
    <div id="edit_project" class='p-8 bg-white shadow rounded-3xl'>
      <h2 class="py-4 my-4 text-2xl tracking-wider text-center text-white bg-purple-400 rounded-2xl " >編輯專案</h2>
      <%= form_for(@project) do |form| %>
        <div class="form-list">
          <%= form.label :organizer, "提案組織 *", class:"form-list-label" %>
          <%= form.text_field :organizer, placeholder: "您的組織名稱", class:"form-list-field input-focus" %>
        </div>
        <div class="form-list">
          <%= form.label :email, "電子信箱 *", class:"form-list-label" %>
          <%= form.email_field :email, placeholder: "請確認您的電子信箱", class:"form-list-field input-focus" %>
        </div>
        <div class="form-list">
          <%= form.label :phone, "聯絡電話 *", class:"form-list-label" %>
          <%= form.telephone_field :phone, placeholder: "您的手機號碼，電話號碼請加入區碼", class:"form-list-field input-focus" %>
        </div> 
        <div class="form-list">
          <%= form.label :title, "提案名稱 *", class:"form-list-label" %>
          <%= form.text_field :title, placeholder: "可日後變更", class:"form-list-field input-focus" %>
        </div> 
        <div class="form-list">
          <%= form.label :amount_target, "提案目標金額 *", class:"form-list-label" %>
          <%= form.text_field :amount_target, placeholder: "團隊可簡略試算集資成本、生產或資金的運用，以推算出集資的門檻", class:"form-list-field input-focus" %>
        </div> 
        <div class="form-list">
          <%= form.label :end_time, "提案結束日期 *", class:"form-list-label" %>
          <%= form.date_field :end_time, class: "ml-5 input-focus col-span-2" %>
        </div>
        <div class="form-list">
          <div class='col-span-4 border-r-2 border-purple-300 primary-text-color'>
            <%= form.label :avatar, "封面照片 *", class:"" %>
            <p class='text-sm text-gray-400 '>請使用.png, .jpeg, .jpg, .webp, .gif</p>
          </div>
          <%= form.file_field :avatar , class: "ml-5 input-focus col-span-6"%>
        </div>
        <div class="px-6 py-6 mb-4 border-2 border-purple-300 border-solid">
            <%= form.label :description, "提案描述 *", class:"text-purple-400" %>
            <p class='mb-2 text-sm text-gray-400 '>附件圖片請使用.png, .jpeg, .jpg, .webp, .gif</p>
            <%= form.rich_text_area :description , class:"input-focus" %>
        </div>
        <%= form.submit "確認送出", class:"field bg-purple-400 hover:bg-purple-600 w-full rounded px-6 py-2 text-white" %>
      <% end %>
    </div>
  </div>
</main>


app/views/projects/follow.js.erb
$("#follow-<%= follow.followable_id %>").remove();

app/views/projects/index.html.erb
<main id='searchPage' class='bg-gray-50'>
      <%= javascript_pack_tag 'SearchPage' %>
</main>

app/views/projects/new.html.erb
<main class='py-10 wave-bg'>
  <%= render 'donate_items/input_errors', object: @project %>
  <section id="new_project" class='max-w-3xl p-8 py-12 mx-auto bg-white rounded-3xl'>
      <h2 class="py-4 my-4 text-2xl tracking-wider text-center text-white bg-purple-400 rounded-2xl" >我想在Wubay提案</h2>
      <%= form_for(@project) do |form| %>
        <div class="form-list">
          <%= form.label :organizer, "提案組織 *", class:"form-list-label" %>
          <%= form.text_field :organizer, placeholder: "您的組織名稱", class:"form-list-field input-focus" %>
        </div>
        <div class="form-list">
          <%= form.label :email, "電子信箱 *", class:"form-list-label" %>
          <%= form.email_field :email, placeholder: "請確認您的電子信箱", class:"form-list-field input-focus" %>
        </div>
        <div class="form-list">
          <%= form.label :phone, "聯絡電話 *", class:"form-list-label" %>
          <%= form.telephone_field :phone, placeholder: "您的手機號碼，電話號碼請加入區碼", class:"form-list-field input-focus" %>
        </div> 
        <div class="form-list">
          <%= form.label :title, "提案名稱 *", class:"form-list-label" %>
          <%= form.text_field :title, placeholder: "可日後變更", class:"form-list-field input-focus" %>
        </div> 
        <div class="form-list">
          <%= form.label :amount_target, "提案目標金額 *", class:"form-list-label" %>
          <%= form.text_field :amount_target, placeholder: "團隊可簡略試算集資成本、生產或資金的運用，以推算出集資的門檻", class:"form-list-field input-focus" %>
        </div> 
        <div class="form-list">
          <%= form.label :end_time, "提案結束日期 *", class:"form-list-label" %>
          <%= form.date_field :end_time, class: "ml-5 input-focus col-span-2" %>
        </div>
        <div class="form-list">
          <div class='col-span-4 border-r-2 border-purple-300 primary-text-color'>
            <%= form.label :avatar, "封面照片 *", class:"" %>
            <p class='text-sm text-gray-400 '>請使用.png, .jpeg, .jpg, .webp, .gif</p>
          </div>
          <%= form.file_field :avatar , class: "ml-5 input-focus col-span-6"%>
        </div>
        <div class="px-6 py-6 mb-4 border-2 border-purple-300 border-solid">
            <%= form.label :description, "提案描述 *", class:"text-purple-400" %>
            <p class='mb-2 text-sm text-gray-400 '>附件圖片請使用.png, .jpeg, .jpg, .webp, .gif</p>
            <%= form.rich_text_area :description , class:"input-focus" %>
        </div>
        <%= form.submit "確認送出", class:"field bg-purple-400 hover:bg-purple-600 w-full rounded px-6 py-2 text-white" %>
      <% end %>
  </section>
</main>

app/views/projects/show.html.erb
<main>
  <article>
    <div class="pt-10 bg-gray-100">
      <h1 class="mb-3 text-2xl font-semibold text-center"><%= @project.title %></h1>
      <p class="text-center">提案組織 <span class="primary-text-color"><%= @project.organizer %></span></p>
    </div>
    <section class='py-10 bg-gray-100'>
      <div class='max-w-6xl grid-cols-10 gap-8 px-10 mx-auto lg:grid lg:px-5'>
        <div class='col-span-6'>
          <div class="projects-img-box">
            <div class='fit-size'>
              <% if @project.avatar.attached? %>
                  <%= image_tag @project.avatar.variant(resize_to_limit: [1000, 500]), :class=> "object-cover w-full h-full rounded-3xl", :alt=> '專案照片' %>
                <% else %>
                  <%= image_tag 'wubay.png' %>
              <% end %>
            </div>                    
          </div>
        </div>
        <div class="col-span-4" >
          <p class="my-2 text-3xl font-semibold">NT$ <%= @project.current_total %></p>
          <div class="progress-container">
            <span id="progressPercent">0%</span>
            <div class="progress-bar" data-controller='progressBar' data-percentage='<%= @percentage %>'></div>
          </div>
          <P class="my-2">目標金額：<%= @project.amount_target %></P>
          <p class="my-2 font-semibold" data-controller='leftTimer' data-percentage="<%= @percentage %>" data-project-time="<%= @project.end_time %>">
            剩餘時間：<span id='leftTime' data-leftTimer-target='leftTime'></span>
          </p>
          <P class="my-2 font-semibold">贊助人數：<%= @donate_users_count %> 人</P>
          <p class="my-2 font-semibold" data-controller='projectTime' data-end-time='<%= @project.end_time %>' data-created-time='<%= @project.updated_at%>'></p>
          <div class="flex" data-controller="copyURL">
            <input data-copyURL-target='URL' type="text" class='flex-1 p-2 text-gray-500 bg-purple-100 border border-purple-300 rounded-lg outline-none'>
            <button id='copybtn' class="px-3 text-white bg-purple-400 rounded-lg" data-action='click->copyURL#copy'><i class="fa-solid fa-copy"></i></button>
          </div>
          <div class="grid grid-cols-2 gap-4 mt-4 donate-box">
            <button class="col-span-1 py-2 duration-200 border border-gray-400 rounded-lg hover:bg-purple-400 hover:text-white"
            data-controller='follow' 
            data-action='click->follow#followUp' 
            data-follow-target='followButton'
            data-project-id='<%= @project.id %>'>
              <span><%= @follow_state %></span>
            </button>
            <%= link_to '贊助專案', project_donate_items_path(@project), :class => "col-span-1 py-2 text-center text-white bg-purple-400 rounded-lg hover:bg-purple-300 donate-link" %>
          </div>
        </div>
      </div>
    </section>
    <div class='sticky top-0 z-10 bg-white border-t-2 border-b-2 border-gray-300 border-double'>
      <div class="justify-between max-w-6xl mx-auto text-sm md:text-base lg:flex">
        <div class="flex items-center justify-center h-16 font-semibold text-gray-400">
          <%= link_to '專案內容', project_path(@project), class:"current-page mx-2 md:mx-5"%>
          <a href='<%= project_questions_path(@project)%>' class="mx-2 md:mx-5">
            常見問題 <span class='text-xs align-top'><%= @project.questions.count%></span>
          </a>
          <a href='<%= project_comments_path(@project)%>' class="mx-2 md:mx-5">
            留言專區 <span class='text-xs align-top'><%= @project.comments.count%></span>
          </a>
          <%= link_to '即時通訊', project_messages_path(@project), class:"mx-2 md:mx-5"%>
        </div>  
        <% if @project.user_id == current_user&.id %>
          <div class='flex items-center justify-center mb-4 lg:my-3'>
            <%= link_to "編輯專案", edit_project_path, class:'mx-5 p-2 inline-block border border-purple-400 rounded-xl ' %>
            <%= link_to "刪除專案", project_path, method: "delete", data: {confirm: '確定要刪除嗎?'}, class:'text-red-400 mr-5'%>
          </div>
        <% end %>
      </div>
    </div>
    <section class="py-8 ">
      <div class="max-w-6xl grid-cols-10 gap-12 p-5 mx-auto lg:grid" data-controller="projectUnroll">
        <div class='relative h-64 col-span-7 overflow-hidden project-content lg:h-auto' data-projectUnroll-target="projectContent" >
          <div class="break-all translucent-cover lg:hidden" data-projectUnroll-target="translucentCover"></div>
          <%= @project.description%>
        </div>
        <div class="h-12 unrollBtn lg:hidden" data-projectUnroll-target="unrollBtn">
          <button class="block w-full h-full text-centertext-purple-300" data-action="click->projectUnroll#unroll">點擊查看詳細內容</button>
        </div>
        <div class="col-span-3 ">
          <div class='p-3 overflow-x-hidden lg:sticky top-20 lg:overflow-y-auto lg:h-screen'>
            <article class='w-full p-4 mb-3 border border-gray-300 border-solid rounded-xl'>
            <div class='flex'>
              <% if @project.user.avatar_url != nil %>
              <%= image_tag(@project.user.avatar_url, :class=> "rounded-2xl h-20 w-20 mr-3") %>
            <% else %>
              <%= image_tag 'avatar1.png', class: 'rounded-2xl h-20 w-20 mr-3' %>
            <% end %>
              <div>
                <h2 class='mb-3 text-xl primary-text-color'><%= @project.organizer %></h2>
                <i class="mr-2 text-2xl fa-brands fa-square-facebook"></i>
                <i class="text-2xl fa-brands fa-instagram"></i>
              </div>
            </div>
            <p class='mb-3 break-words'><%= @project.user.description%></p>
            </article>
            <% if @project.user_id == current_user&.id %>
              <div class='py-4 mb-3 tracking-wider border border-purple-300 border-double'>
                <%= link_to "新增贊助方案", new_project_donate_item_path(@project), class:'block text-xl text-center primary-text-color tracking-wider ' %>
                </div>
            <% end %>
            <div class='donate-items'>
              <%= render partial: 'donate_items/donate_item', donate_items: @donate_items %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </article>
</main>

