config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: 'users/sessions', passwords: 'users/passwords' } 
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/profile', to: 'users/registrations#profile'
  end
  get '/users/projects/:id', to: 'projects#show'
  resources :projects do
    resources :donate_items
    resources :messages, only: %i[index create]
    member do
      post :follow
    end
    resource :disclosures, only: [:show]
    resources :comments, shallow: true
    resources :questions, shallow: true, except: [:show]
  end
  namespace :api do
    resources :comments, only: [] do
      member do
        post :like
      end
    end
    resource :search, only: [] do 
      collection do
        get :projects
      end 
    end
  end
  resources :follows, only: [:index] 
  resources :transactions, only: [:index, :create, :destroy] do
    collection do
      post :paid
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('wubaytitle.ico') %>
    <title>Wubay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application_footer', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'additional_donate', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application'%>
    <script src="https://kit.fontawesome.com/4b775a86e6.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header class='header'>
      <h1 class='sr-only'>wubay,讓你夢想超越五倍</h1>
      <% if notice %>
        <div class="py-4 text-xl font-semibold tracking-wider text-center text-green-600 bg-green-100 notice" data-controller="message">
          <%= notice %>
        </div>
      <% end %>
      <div class="w-full text-lg border-b border-gray-200 text-slate-500 ">
        <nav class="relative flex items-center justify-between max-w-6xl mx-auto header-item h-70">
          <div class="header-webnav">
            <ul class="hidden lg:flex ">
              <li><%= link_to "首頁", root_path, class:"mx-5 hover:text-gray-400"%></li>
              <li><%= link_to "探索", projects_path, class:"mx-5 hover:text-gray-400"%></li>
              <li><%= link_to "提案", new_project_path, class:"mx-5 hover:text-gray-400"%></li>
            </ul>
            <!-- 手機側邊收縮導覽列 -->
            <input id="mobile-nav-switch" type="checkbox" class="hidden" />
            <label for="mobile-nav-switch" id='mobile-nav-btn' class="ml-8 text-2xl lg:hidden">
              <span class="inline-block"><i class="fa-solid fa-align-justify"></i></span>
              <span class="hidden"><i class="fa-solid fa-angle-left"></i></span>
            </label>
            <div class="absolute z-50 w-full px-16 text-gray-500 bg-white border-2 border-gray-200 mobile-nav top-20 py-7 lg:hidden">
              <div class="mb-3 text-2xl">
                <%= link_to "首頁", root_path, class:"px-4 pb-2 block"%>
                <%= link_to "探索", projects_path, class:"px-4 pb-2 block"%>
              </div>
              <div class="mb-3">
                <h2 class="font-bold primary-text-color">Proposal</h2>
                <%= link_to "提案", new_project_path, class:"px-4 block py-4 text-2xl"%>
              </div>
              <div class="mb-3">
                <h2 class="font-bold primary-text-color">Member</h2>
                <ul class="px-4 text-2xl">
                  <% if user_signed_in? %>
                    <li class='py-2'><%= link_to "個人頁面",users_profile_path %></li>
                    <li class='py-2'><%= link_to "交易紀錄", transactions_path %></li>
                    <li class='py-2'><%= link_to "追蹤專案", follows_path %></li>
                    <li class='py-2'><%= link_to "編輯個人資料", edit_user_registration_path %></li>
                    <li class='py-2'><%= link_to "登出", destroy_user_session_path, method: 'delete'%></li>
                  <% else %>
                    <%= link_to "登入", new_user_session_path, class:"block py-2"%>
                    <%= link_to "註冊", new_user_registration_path, class:"block py-2" %>
                  <% end %>
                </ul>
              </div>
              <div class="flex justify-center">
                <div>
                  <p>Copyright ©2022 Wubay <br/> All rights reserved</p>
                </div>
              </div>
            </div>
          </div>
          <!-- LOGO -->
          <div class="absolute w-40 transform translate-x-1/2 right-1/2">
            <a href="/" alt='wubay，讓你的夢想超越五倍'><%= image_tag('wubay.png')%></a>
          </div>
          <%# 搜尋及會員相關 %>
          <div class="flex items-center">
            <div id="searchBar">
              <%= javascript_pack_tag 'SearchBar' %>
            </div>
              <!-- 會員相關  -->
            <div class="relative mr-6 member primary-text-color" data-controller='memberSwitch'>
              <div class='items-center hidden lg:flex'>
                <% if user_signed_in? %>
                  <button class="px-5 py-2 ml-6 text-white bg-purple-400 border-4 border-white border-double rounded-full" data-action="click->memberSwitch#switch" data-memberSwitch-target="button"><i class="text-xl fa-regular fa-user"></i></button>
                <% else %>
                  <%= link_to "登入", new_user_session_path, class:"mx-5"%>
                  <%= link_to "註冊", new_user_registration_path, class:"px-5 py-3 rounded-md border border-purple-400 hover:bg-purple-400 hover:text-white duration-300" %>
                <% end %>
              </div>
              <%# 收合會員功能 %>
              <div class='absolute right-4 bg-white z-50 rounded-lg shadow-2xl 	box-shadow: 0 0 20px 10px rgb(0 0 0) hidden' data-memberSwitch-target="memberCenter">
                <ul class='w-40 py-2 text-sm primary-text-color'>
                  <li class='py-2 pl-4 border-b border-gray-200'><%= link_to "個人頁面",users_profile_path, class:'hover:text-purple-300' %></li>
                  <li class='py-2 pl-4'><%= link_to "交易紀錄", transactions_path, class:'hover:text-purple-300' %></li>
                  <li class='py-2 pl-4 border-b border-gray-200'><%= link_to "追蹤專案", follows_path, class:'hover:text-purple-300'%></li>
                  <li class='py-2 pl-4'><%= link_to "編輯個人資料", edit_user_registration_path, class:'hover:text-purple-300' %></li>
                  <li class='py-2 pl-4'><%= link_to "登出", destroy_user_session_path, method: 'delete', class:'hover:text-purple-300'%></li>
                </ul>
              </div>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <%= yield %> 
    <footer class="py-10 text-sm border-t-2 border-gray-200 md:pt-20">
      <div class='max-w-6xl px-2 mx-auto md:px-10'>
        <h2 id='title' class='mb-3 text-2xl text-center primary-text-color'><wubay-team></wubay-team></h2>
        <div id='contributors'></div> 
        <div class='my-6 text-4xl text-center'>
          <a href='https://github.com/WaBay-fantastic-winner/wubay' ><i class="fa-brands fa-github"></i></a>
        </div>
        <div class="my-5 text-center">
          <p>Copyright ©2022 Wubay <br/> All rights reserved</p>
        </div>
      </div>
    </footer>
  </body>
</html>